name: 'Deploy lambda function'
description: 'Create and/or update lambda function'
author: 'MrAtheist'
inputs:
  app_name:
    description: 'Lambda function name'
  deploy_config:
    required: true
    description: 'Lambda config, based from $src_dir, i.e. "src/projectA/config.json"; must have "zip_include" node to specify the zip content: "zip_include": [index.js, ./src]'
  node_env:
    description: 'NODE_ENV'
  node_app_instance:
    description: 'NODE_APP_INSTANCE'
  package_lock_chksum:
    description: 'Checksum for package-lock.json'
  repository:
    description: 'Github repository'
  src_dir:
    description: 'Source directory'
    default: './'
  fetch-depth:
    default: 1
    required: false
    description: 'Number of commits to fetch during checkout. 0 indicates all history for all branches and tags.'

outputs:
  IAM_USER: # id of output
    description: 'IAM_USER'

runs:
  using: 'docker'
  image: 'Dockerfile'
